[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox.toml"
]

[font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[cursor]
style = "Beam"

[window]
opacity = 0.9
startup_mode = "Windowed"
dynamic_padding = true
resize_increments = true

[window.padding]
x = 0
y = 0

